name: initramfs_tools
check_this_dir: /etc/initramfs-tools
enable_lvm:
  - echo "This operations not required."
enable_luks:
  - echo "This operations not required."
commands:
  - update-initramfs -c -t -k all
